language: cpp
sudo: true
dist: xenial
matrix:
  include:
  - os: osx
    osx_image: xcode9
    env:
    - MATRIX_EVAL="CC=clang && CXX=clang++"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
#Added power jobs
  - os: linux
    arch: ppc64le
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-6
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
  - os: linux
    arch: ppc64le
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: linux
    arch: ppc64le
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - cmake
    env:
    - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
   
before_install:
  - eval "${MATRIX_EVAL}"
  - ./ci/setup_${TRAVIS_OS_NAME}_environment.sh
  - | 
   if [[ "$TRAVIS_CPU_ARCH" == "ppc64le" ]]; then
     sudo apt install curl gnupg
     curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
     sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
     echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
     sudo apt update && sudo apt install bazel
     sudo apt install openjdk-8-jdk
   fi
script:
  - mkdir -p build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON ..
  - make
  - make test
  - cd ..
  - bazel build //...
  - bazel test //...
